### PR TITLE
Feature/add remove options

### PR DESCRIPTION
**Pull request by Simounet**
I added the ability to:
- add / remove option and optgroup from PHP
- set the name from a simple string instead of a serialized object

YOUHOU !!!!

### CODE REVIEW

**Comment by mkalam-alami** [comment]
+1 for merging

**Comment by rey0bs** [comment]
+1 for merging ! Amazing feature !

**Comment by Simounet** [comment]
Thanks pals. :dancers:

**Comment by Simounet** [comment]
Yeah! :v:

**Pull request merged**
